#!/bin/sh
#
#    50-ferryheader - create the Ferry MOTD header
#    Copyright (C) 2014 OpenCore LLC
#
#    Authors: James Horey <jlh@opencore.io>
#    Licensed under the Apache License, Version 2.0 (the "sLicense");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

echo ''
echo '   _       __     __                             __      '
echo '  | |     / /__  / /________  ____ ___  ___     / /_____ '
echo '  | | /| / / _ \/ / ___/ __ \/ __ `__ \/ _ \   / __/ __ \'
echo '  | |/ |/ /  __/ / /__/ /_/ / / / / / /  __/  / /_/ /_/ /'
echo '  |__/|__/\___/_/\___/\____/_/ /_/ /_/\___/   \__/\____/ '
echo '    ______                     '
echo '   / ____/__  ____________  __ '
echo '  / /_  / _ \/ ___/ ___/ / / / '
echo ' / __/ /  __/ /  / /  / /_/ /  '
echo '/_/    \___/_/  /_/   \__, /   '
echo '                     /____/    '
echo ''
