#!/bin/sh
#
#    50-ferryheader - create the Ferry MOTD header
#    Copyright (C) 2014 OpenCore LLC
#
#    Authors: James Horey <jlh@opencore.io>
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

GREEN='\e[0;32m'
NC='\e[0m'

echo -e "${GREEN}   _       __     __                             __      ${NC}"
echo -e "${GREEN}  | |     / /__  / /________  ____ ___  ___     / /_____ ${NC}"
echo -e "${GREEN}  | | /| / / _ \/ / ___/ __ \/ __ `__ \/ _ \   / __/ __ \${NC}"
echo -e "${GREEN}  | |/ |/ /  __/ / /__/ /_/ / / / / / /  __/  / /_/ /_/ /${NC}"
echo -e "${GREEN}  |__/|__/\___/_/\___/\____/_/ /_/ /_/\___/   \__/\____/ ${NC}"
echo -e ""
echo -e "${GREEN}    ______                     ${NC}"
echo -e "${GREEN}   / ____/__  ____________  __ ${NC}"
echo -e "${GREEN}  / /_  / _ \/ ___/ ___/ / / / ${NC}"
echo -e "${GREEN} / __/ /  __/ /  / /  / /_/ /  ${NC}"
echo -e "${GREEN}/_/    \___/_/  /_/   \__, /   ${NC}"
echo -e "${GREEN}                     /____/    ${NC}"
echo -e ""
