#!/bin/bash

source /service/sbin/setup

if [ $1 == "init" ]; then 
    create_fuse_dev
    set_ip_address $2

    cat /service/keys/id_rsa.pub >> /root/.ssh/authorized_keys
    /usr/sbin/sshd -D
else
    for f in /service/runscripts/$1/*
    do
	$f $2 $3
    done
fi
