#! /bin/bash

source /service/sbin/setup

if [ $1 == "init" ]; then 
    /service/sbin/init01.sh
elif [ $1 == "halt" ]; then 
    /service/sbin/halt01.sh
elif [ $1 == "start" ]; then 
    # Change the file ownership back to ferry user. This is 
    # necessary since the host may not have the ferry user. 
    chown -R ferry:ferry /service/data
    chown -R ferry:ferry /service/logs

    # Start the mongo server
    LC_ALL=C
    su ferry -c 'mongod --config /service/conf/mongodb/mongodb.conf' >> /service/logs/start.log
elif [ $1 == "stop" ]; then 
    # Shutdown MongoDB. 
    su ferry -c 'mongod --config /service/conf/mongodb/mongodb.conf --shutdown'
fi