#!/bin/bash

source /service/sbin/setup

if [ $1 == "init" ]; then 
    /service/sbin/init01.sh
elif [ $1 == "halt" ]; then 
    /service/sbin/halt01.sh    
elif [ $1 == "hosts" ]; then 
    pophosts
elif [ $1 == "start" ]; then 
    su ferry -c 'nohup /titan/packages/rexster-server/bin/rexster.sh -s -c /titan/conf/rexster.xml > /titan/data/rexster.log 2> /titan/data/rexster.err &'
elif [ $1 == "restart" ]; then 
    su ferry -c 'nohup /titan/packages/rexster-server/bin/rexster.sh -s -c /titan/conf/rexster.xml > /titan/data/rexster.log 2> /titan/data/rexster.err &'
elif [ $1 == "stop" ]; then 
    su ferry -c 'pkill -f rexster'
fi
