#!/bin/bash

source /service/sbin/setup

if [ $1 == "init" ]; then 
    /service/sbin/init01.sh
elif [ $1 == "halt" ]; then 
    /service/sbin/halt01.sh    
elif [ $1 == "hosts" ]; then 
    pophosts
else
    for f in /service/runscripts/$1/*
    do
	$f $2 $3
    done
fi
