#!/bin/bash

function create_fuse_dev {
    # We'll need to create /dev/fuse since we removed 
    # it during the installation (since build doesn't support
    # privileged operations)
    if [ ! -e /dev/fuse ]; then
	mknod /dev/fuse c 10 229
    fi
}

if [ $1 == "listen" ]; then 
    create_fuse_dev
    cat /service/keys/id_rsa.pub >> /root/.ssh/authorized_keys
    /usr/sbin/sshd -D
else
    for f in /service/runscripts/$1/*
    do
	$f $2 $3
    done
fi
