#!/bin/bash

source /service/sbin/setup

if [ $1 == "init" ]; then 
    /service/sbin/init01.sh
elif [ $1 == "halt" ]; then 
    /service/sbin/halt01.sh    
elif [ $1 == "hosts" ]; then 
    pophosts
elif [ $1 == "start" ]; then 
    /usr/sbin/glusterd &
    /service/configuration/configure start
elif [ $1 == "restart" ]; then 
    /usr/sbin/glusterd &
    /service/configuration/configure restart
elif [ $1 == "stop" ]; then 
    # Stop the gluster volume
    /service/configuration/configure stop

    # Stop the gluster daemon
    pkill -f glusterd
elif [ $1 == "clean" ]; then 
    /service/configuration/configure clean    
fi
