#!/bin/bash

if [ $1 == "start" ]; then 
    # Configure the master node. 
    /service/configuration/configure start
elif [ $1 == "listen" ]; then 
    # Make sure the public key is authorized.
    cat /service/keys/id_rsa.pub >> /root/.ssh/authorized_keys
    
    # Start the gluster server
    /usr/sbin/glusterd &
    /usr/sbin/sshd -D
elif [ $1 == "stop" ]; then 
    # Stop the gluster volume
    /service/configuration/configure stop

    # Stop the gluster daemon
    pkill -f glusterd

    # Now stop the ssh daemon. 
    pkill -f sshd
fi
